directory:
  C:\Users\edwardbs\Documents\Rose Documents\CSSE375\project-repo\Team6JavaLinter\src\test\resources\DataClassDummyData

checks:
  PoorNamingConvention: true
  EqualsHashCode: true
  SingleResponsibilityPrinciple: true
  InformationHidingViolation: true
  SingletonPattern: true
  DecoratorPattern: true
  StrategyPattern: true
  RedundantInterface: true